radhatam/radhatam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('radhatamapp.urls')),
]

radhatam/radhatamapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'radhatamapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('entity/<str:action>/<int:id>', views.entity, name='entity'),
    path('datascience/<str:action>/<int:id>', views.datascience, name='datascience'),
    path('edit_fieldtype/<int:id>', views.edit_fieldtype, name='edit_fieldtype'),
]

radhatam/radhatamapp/models.py
from django.db import models

# Create your models here.
DATA_TYPES = (
    ('TEXT', 'Text'),
    ('INTEGER', 'Integer'),
    ('NUMERIC', 'Numeric'),
    ('DATE', 'Date'),
    ('BINARY', 'Binary'),
    ('PNG_IMAGE', 'PNG Image'),
    ('COLUMN', 'Column'),
    ('DERIVED', 'Derived'),
)


FUNCTION_TYPES = (
    ('CALCULATION', 'Calculation'),
    ('VISUALIZE', 'Visualize'),
    ('DATASCIENCE', 'DataScience'),
)

OP_TYPES = (
    ('EXACT', 'EXACT'),
    ('NOT', 'NOT'),
    ('LT','LESS THAN')

)

SQL_OP_TYPES = {'EXACT': '=', 'NOT': '!=','LT':'<'}


class Entity(models.Model):
    name = models.CharField(max_length=30, unique=True)
    # child = models.ForeignKey('self',on_delete=models.DO_NOTHING,null=True)

    def __str__(self):
        return self.name


class FunctionMeta(models.Model):
    name = models.CharField(max_length=30)
    type = models.CharField(
        max_length=20, choices=FUNCTION_TYPES, default='CALCULATION')
    return_type = models.CharField(
        max_length=20, choices=DATA_TYPES, default='TEXT')
    return_sql = models.CharField(max_length=1024)

    def __str__(self):
        return self.name


class ArgumentMeta(models.Model):
    function = models.ForeignKey(
        FunctionMeta, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30)
    type = models.CharField(max_length=20, choices=DATA_TYPES, default='TEXT')

    def __str__(self):
        return self.name


class Field(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, null=True)
    actual_name = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    main = models.BooleanField(default=False)
    type = models.CharField(max_length=64, choices=DATA_TYPES, default='TEXT')
    child_entity_id = models.IntegerField(null=True)
    child_field_id = models.IntegerField(null=True)
    derived_level = models.IntegerField(default=0)
    function = models.ForeignKey(
        FunctionMeta, on_delete=models.DO_NOTHING, null=True)
    # order = models.IntegerField()

    def __str__(self):
        return self.name


class FieldFilter(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, null=False)
    filter_col = models.CharField(max_length=30, null=False)
    filter_op = models.CharField(
        max_length=30, null=False, choices=OP_TYPES, default='EXACT')
    filter_val = models.CharField(max_length=120, null=False)


class DerivedFieldArgument(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE, null=True)
    argument_name = models.CharField(max_length=30, null=True)
    argument_value = models.CharField(max_length=30, null=True)
    argument_type = models.CharField(max_length=30, null=True)

radhatam/radhatamapp/forms.py
from django import forms

class UploadFileForm(forms.Form):
    name = forms.CharField(max_length=50)
    csv_file = forms.FileField()

class UploadFileDataForm(forms.Form):   
    csv_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class DerivedColumnForm(forms.Form):
    name = forms.CharField(max_length=50)

radhatam/radhatamapp/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from django.contrib import messages
from .forms import UploadFileForm, UploadFileDataForm, DerivedColumnForm
import pandas as pd
import pygwalker as pyg
from io import StringIO
import logging
from .models import Entity, Field, DATA_TYPES, SQL_OP_TYPES, FunctionMeta, ArgumentMeta, DerivedFieldArgument, FieldFilter
from django.db import connection
from django.conf import settings
import psycopg2
from sqlalchemy import create_engine

logger = logging.getLogger(__name__)
# Create your views here.

PG_NAME = settings.DATABASES['default']['NAME']
PG_USER = settings.DATABASES['default']['USER']
PG_PWD = settings.DATABASES['default']['PASSWORD']
PG_HOST = settings.DATABASES['default']['HOST']
PG_PORT  = settings.DATABASES['default']['PORT']


conn = psycopg2.connect(dbname=PG_NAME, user=PG_USER, password=PG_PWD,host=PG_HOST,port=PG_PORT)
engine = create_engine(f"postgresql+psycopg2://{PG_USER}:{PG_PWD}@{PG_HOST}/{PG_NAME}")

def index(request):
    entities = Entity.objects.all()
    return render(request, 'radhatamapp/index.html', context={'entities': entities})


def entity(request, action, id):
    data = {}
    if "GET" == request.method:
        entity = None
        fields = None
        if id:
            entity = Entity.objects.get(id=id)
            fields = Field.objects.filter(entity__id=id)

        form = UploadFileForm()
        dataupload_form = UploadFileDataForm()
        entities = Entity.objects.exclude(id=id).all()
        return render(request, "radhatamapp/entity.html", context={'form': form, 'entity': entity, 'entities': entities, 'fields': fields, 'dtypes': DATA_TYPES, 'dataupload_form': dataupload_form})
    # if not GET, then proceed
    if action == 'create':
        try:
            name = request.POST['name']
            csv_file = request.FILES["csv_file"]

            file_data = csv_file.read().decode("utf-8")
            cols = StringIO(file_data).readlines()[0].split(',')
            if id == 0:
                Entity.objects.filter(name=name).delete()
            entity = Entity.objects.create(name=name)
            entity.save()
            for col in cols:
                name = col.replace('.', '').replace(
                    '-', '_').replace("'", "").replace('"', '').replace(' ', '_').lower()
                Field.objects.create(
                    actual_name=col, name=name, entity=entity).save()
            # create an additinal file_name columnf
            Field.objects.create(
                actual_name=f'{entity.name}_file_name',
                name=f'{entity.name}_file_name', entity=entity).save()
            return HttpResponseRedirect(f'/entity/display/{entity.id}')
        # return HttpResponseRedirect(reverse("radhatamapp:create_entity"))

        except Exception as e:
            logging.getLogger("error_logger").error(
                "Unable to upload file. "+repr(e))
            messages.error(request, "Unable to upload file. "+repr(e))
    if action == 'create_table':
        entity = Entity.objects.get(id=id)
        fields = Field.objects.filter(entity__id=id)
        sql = f"create table if not exists {entity.name}("
        for field in fields:
            sql += f"{field.name} {field.type},"
        sql = f"{sql[:-1]})"
        execute_raw_query(f"drop table if exists {entity.name}")
        execute_raw_query(sql)
    if action == 'uploaddata':
        try:
            csv_files = request.FILES.getlist('csv_file')
            print(csv_files)

            entity = Entity.objects.get(id=id)
            fields = Field.objects.filter(entity__id=id)

            for csv_file in csv_files:
                print(csv_file)
                file_data = csv_file.read().decode("utf-8")
                file = StringIO(file_data).readlines()
                cols = file[0].split(',')
                columns = []
                for col in cols:
                    name = replace_clean(col).lower()
                    columns.append(name)

                columns.append(f'{entity.name}_file_name')

                sql_cols = f"({(',').join(columns)})"
                for line in file[1:]:
                    # next(line)
                    vals = line.split(',')
                    field_sql = ''

                    for i, c in enumerate(vals):
                        if c.isdecimal() or c.isdigit() or c.isnumeric() or c.replace('.', '', 1).isdigit():
                            field_sql += f"{c},"
                        else:
                            c = c.replace("'", "")
                            field_sql += f"'{c}',"

                    field_sql = f"{field_sql}'{csv_file.name}'"
                    sql = f"insert into {entity.name} {sql_cols} values({field_sql})"
                    execute_raw_query(sql)
                    # break

            
        # return HttpResponseRedirect(reverse("radhatamapp:create_entity"))

        except Exception as e:
            logging.getLogger("error_logger").error(
                "Unable to upload file. "+repr(e))
            messages.error(request, "Unable to upload file. "+repr(e))
        return HttpResponseRedirect(f'/entity/display/{id}')
    if action == 'add_child':
        print(request.POST)
        if request.POST['child_entity_id'] and not request.POST['child_field_id']:
            child_entity_name = request.POST['child_entity_id']
            entity = Entity.objects.get(id=child_entity_name)
            fields = Field.objects.filter(entity__id=entity.id)
            html = '<option></option>'
            for field in fields:
                html += f"<option value='{field.id}'>{field.name}</option>"
            return HttpResponse(html)
        else:
            parent_field_id = request.POST['parent_field_id']
            child_entity_id = request.POST['child_entity_id']
            child_field_id = request.POST['child_field_id']
            parent_field = Field.objects.get(id=parent_field_id)
            parent_field.child_entity_id = child_entity_id
            parent_field.child_field_id = child_field_id
            parent_field.save()

            # field = Field.objects.get(id=parent)
        return HttpResponse("done")
    return HttpResponseRedirect(reverse("radhatamapp:entity", kwargs={'action': 'display', 'id': id}))


def edit_fieldtype(request, id):
    if "POST" == request.method:
        print(id, request.POST)
        field_name = None
        dtype = None
        for k, v in request.POST.items():
            field_name = k
            dtype = v

        field = Field.objects.get(id=id)
        field.type = dtype
        field.save()
        return HttpResponse("<option>selected</option>")


def datascience(request, action, id):
    print("***********************************")
    print(action, id)
    print("***********************************")
    data = {}
    entity = Entity.objects.get(id=id)
    if "GET" == request.method:
      

        fields = Field.objects.filter(
            entity=entity, derived_level__gte=1).order_by('derived_level')
        print(fields)

        data_sql = generate_cte_sql(id)
        create_meta_table(entity.name, data_sql)

        full_data_sql = generate_action_sql(data_sql, id, action) + '  order by trade_date desc limit 200'
        data, col_names = fetch_raw_query(full_data_sql)
        entity_columns_meta = get_table_columns(f"{entity.name}_meta")
        level_field = get_level_of_fields(id)
        functions_calc_meta = FunctionMeta.objects.filter(type='CALCULATION')
        functions_viz_meta = FunctionMeta.objects.filter(type='VISUALIZATION')
        functions_ds_meta = FunctionMeta.objects.filter(type='DATASCIENCE')

        filters = FieldFilter.objects.filter(entity=entity)

        if action == 'apply_table_filter':
            print(request.GET)
            fieldFilters = FieldFilter.objects.filter(entity=entity)
            new_filter_col = request.GET.get('filter_col_0')
            new_filter_op = request.GET.get('filter_op_0')
            new_filter_val = request.GET.get('filter_val_0')
            print(new_filter_col, new_filter_op, new_filter_val)

            field_filter_array = []
            if new_filter_col and new_filter_op and new_filter_val:
                field_filter_array = [{'filter_col': new_filter_col,
                                       'filter_op': new_filter_op, 'filter_val': new_filter_val}]

            for fieldFilter in fieldFilters:
                new_filter_col = request.GET.get(
                    f'filter_col_{fieldFilter.id}')
                new_filter_op = request.GET.get(f'filter_op_{fieldFilter.id}')
                new_filter_val = request.GET.get(
                    f'filter_val_{fieldFilter.id}')
                if new_filter_col and new_filter_op and new_filter_val:
                    field_filter_array.append(
                        {'filter_col': new_filter_col, 'filter_op': new_filter_op, 'filter_val': new_filter_val})
            print(field_filter_array)

            # Delete previous objects
            if (new_filter_col and new_filter_op and new_filter_val) or field_filter_array:
                FieldFilter.objects.filter(entity=entity).delete()

            # # create all new
            for field_filter in field_filter_array:
                FieldFilter.objects.create(
                    entity=entity, filter_col=field_filter['filter_col'], filter_op=field_filter['filter_op'], filter_val=field_filter['filter_val'])
            return HttpResponseRedirect(f'/datascience/display/{entity.id}')
        # get all filters
        # fieldFilters = FieldFilter.objects.filter(field__entity=entity)
        # print(fieldFilters)
        # if not GET, then proceed

        # Filter form for table

        # if action == 'get_filter_form':
        #     field = request.GET.get('field')
        #     html = f'<label>{field} = </label>'
        #     field_data_sql = generate_cte_sql(entity.id, field)

radhatam/radhatamapp/templates/radhatamapp/datascience copy.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://global-power-plants.datasettes.com/-/static/app.css?cead5a" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.8.5"></script>

</head>

<body>

    <!-- Button trigger modal -->



    <a href="{% url 'radhatamapp:index' %}">Go back</a>

    <h2>DataScience</h2>
    <div id="indicator" class="htmx-indicator alert alert-success" role="alert">
        <img src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/AjaxLoader.gif" />
    </div>
    
    <div>

        <div>
       
            {% for field_functions in fields %}
            <div class="">Level {{field_functions.derived_level}}</div>
                {{field_functions}}
            {% endfor %}
        </div>
       
        <form hx-indicator="#indicator" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-post="{% url 'radhatamapp:datascience' action='add_derived_field' id=entity.id %}">

            <span class="">Level {{level_field}}</span>
            <input type="number" hidden name="level_field" value="{{level_field}}" />
            <select hx-indicator="#indicator" hx-trigger="change" name="function_id"
                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                hx-post="{% url 'radhatamapp:datascience' action='get_function_params' id=entity.id %}"
                hx-target="#function-form">
                <option></option>
                {% for function in functions_calc_meta %}
            
                <option value="{{function.id}}">{{function.name}}</option>
                {% endfor %}


            </select>
            <div id="function-form"></div>
            <!-- <a href="{% url 'radhatamapp:datascience' action='add_derived_column' id=entity.id %}">Add Derived Fields</a> -->
            <button type="submit">Add</button>
        </form>
    </div>




 

    <!-- Visualize -->
    <!-- <div>
        <form hx-indicator="#indicator" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-post="{% url 'radhatamapp:datascience' action='visualize' id=entity.id %}">

            <span class="">Visualize</span>
            <input type="number" hidden name="level_field" value="{{level_field}}" />
            <select hx-indicator="#indicator" hx-trigger="change" name="function_id"
                hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                hx-post="{% url 'radhatamapp:datascience' action='get_visual_params' id=entity.id %}"
                hx-target="#function-form">
                <option></option>
                {% for function in functions_viz_meta %}
               
                <option value="{{function.id}}">{{function.name}}</option>
                {% endfor %}


            </select>
            <div id="function-form"></div>
            <a href="{% url 'radhatamapp:datascience' action='add_derived_column' id=entity.id %}">Add Derived Fields</a> 
            <button type="submit">Add</button>
        </form>
    </div> -->


    <!-- Tabs -->

    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link  {% if action == 'display' %}active{% endif %}" aria-current="page" href="{% url 'radhatamapp:datascience' action='display' id=entity.id %}">Table</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if action == 'visualize' %}active{% endif %}" href="{% url 'radhatamapp:datascience' action='visualize' id=entity.id %}">Visualization</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if action == 'alert' %}active{% endif %}" href="{% url 'radhatamapp:datascience' action='alert' id=entity.id %}">Alerts</a>
        </li>
      
      </ul>

      {% if action == 'display' %}
    <div class="col-6">
           <!-- Filter -->
    <label>Filter</label>
    <div>
       
        <form  method="GET" action="{% url 'radhatamapp:datascience' action='apply_table_filter' id=entity.id %}">
            {% for filter in filters %}
          
            <div id="filter-form-{{filter.id}}">
                <select name="filter_col_{{filter.id}}">
                    <option></option>
                    {% for field in col_names %}
                    <option value={{field}} {% if field == filter.filter_col %}selected{% endif %}>{{field}}</option>
                    {% endfor %}
                </select>
                <select name="filter_op_{{filter.id}}"> 
                    <option></option>
                    <option value="EXACT" {% if 'EXACT' == filter.filter_op %}selected{% endif %}>=</option>

                    <option value="NOT" {% if 'NOT' == filter.filter_op %}selected{% endif %}>!=</option>

                    <option value="contains" {% if 'contains' == filter.filter_op %}selected{% endif %}>contains</option>

                    <option value="endswith" {% if 'endswith' == filter.filter_op %}selected{% endif %}>ends with</option>

                    <option value="startswith" {% if 'startswith' == filter.filter_op %}selected{% endif %}>starts with
                    </option>

                    <option value="gt" {% if 'gt' == filter.filter_op %}selected{% endif %}>&gt;</option>

                    <option value="gte" {% if 'gte' == filter.filter_op %}selected{% endif %}>≥</option>

                    <option value="lt" {% if 'lt' == filter.filter_op %}selected{% endif %}>&lt;</option>

                    <option value="lte" {% if 'lte' == filter.filter_op %}selected{% endif %}>≤</option>

                    <option value="like" {% if 'like' == filter.filter_op %}selected{% endif %}>like</option>

                    <option value="notlike" {% if 'notlike' == filter.filter_op %}selected{% endif %}>not like</option>

                    <option value="glob" {% if 'glob' == filter.filter_op %}selected{% endif %}>glob</option>

                    <option value="in" {% if 'in' == filter.filter_op %}selected{% endif %}>in</option>

                    <option value="notin" {% if 'notin' == filter.filter_op %}selected{% endif %}>not in</option>

                    <option value="arraycontains" {% if 'arraycontains' == filter.filter_op %}selected{% endif %}>array contains
                    </option>

                    <option value="arraynotcontains" {% if 'arraynotcontains' == filter.filter_op %}selected{% endif %}>array does
                        not contain</option>

                    <option value="date" {% if 'date' == filter.filter_op %}selected{% endif %}>date</option>

                    <option value="isnull" {% if 'isnull' == filter.filter_op %}selected{% endif %}>is null</option>

                    <option value="notnull" {% if 'notnull' == filter.filter_op %}selected{% endif %}>is not null</option>

                    <option value="isblank" {% if 'isblank' == filter.filter_op %}selected{% endif %}>is blank</option>

                    <option value="notblank" {% if 'notblank'  ==  filter.filter_op %}selected{% endif %}>is not blank
                    </option>

                </select>

                <input type="text" name="filter_val_{{filter.id}}" value="{{filter.filter_val}}"/>
                <button hx-target="#filter-form-{{filter.id}}" hx-indicator="#indicator" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
                hx-post="{% url 'radhatamapp:datascience' action='delete_filter' id=entity.id %}?filter_id={{filter.id}}"
                class="btn btn-danger">X</button>
            </div>
            {% endfor %}


            <div>
                <select name="filter_col_0">
                    <option></option>
                    {% for field in col_names %}

                    <option> {{field}}</option>
                    {% endfor %}
                </select>
                <select name="filter_op_0">
                    <option></option>
                    <option value="EXACT">=</option>

                    <option value="NOT">!=</option>

                    <option value="contains">contains</option>

                    <option value="endswith">ends with</option>

                    <option value="startswith">starts with</option>

                    <option value="gt">&gt;</option>

                    <option value="gte">≥</option>

                    <option value="lt">&lt;</option>

                    <option value="lte">≤</option>

                    <option value="like">like</option>

                    <option value="notlike">not like</option>

                    <option value="glob">glob</option>

                    <option value="in">in</option>

                    <option value="notin">not in</option>

                    <option value="arraycontains">array contains</option>

                    <option value="arraynotcontains">array does not contain</option>

                    <option value="date">date</option>

                    <option value="isnull">is null</option>

                    <option value="notnull">is not null</option>

                    <option value="isblank">is blank</option>

                    <option value="notblank">is not blank</option>

                </select>

                <input type="text" name="filter_val_0" />
              
            </div>

            <button type="submit" class="btn btn-success">Apply</button>
        </form>

    </div>

        <table class="table">
            <thead>

                <tr>
                    {% for field in col_names %}
                    <th>{{field}}</th>
                    {% endfor %}
                </tr>

            </thead>
            <tbody>
                {% for d in data %}
                <tr>
                    {% for i in d %}
                    <td>{{i}}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    {% if action == 'visualize' %}
    <div class="col-6">
      visual


    </div>
    {% endif %}

    {% if action == 'alert' %}
    <div class="col-6">
      Alert
    </div>
    {% endif %}
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">

                    <h5 class="modal-title" id="exampleModalLabel">Modal title


                    </h5>
                    <div id="ds-modal-indicator" class="htmx-indicator alert alert-success" role="alert">
                        <img src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/AjaxLoader.gif" />
                    </div>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div class="modal-body">
                    <div id="ds-modal">

                    </div>
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

radhatam/radhatamapp/templates/radhatamapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'radhatamapp:entity' action='create' id=0 %}">Create/Enrich Entity</a>

    <h2>Entities</h2>
    <table>
       
            {% for entity in entities%}
            <tr>
            <td><a href="{% url 'radhatamapp:entity' action='display' id=entity.id %}">{{entity}}</a></td>
        </tr>
            {% endfor %}
 
        
    </table>


    <h2>DataScience</h2>
    <table>
       
            {% for entity in entities%}
            <tr>
            <td><a href="{% url 'radhatamapp:datascience' action='display' id=entity.id %}">{{entity}}</a></td>
        </tr>
            {% endfor %}
 
        
    </table>

</body>
</html>